"""add forwarding events etl

Revision ID: 0f72096cb132
Revises: c703f5e8e0a6
Create Date: 2019-03-23 17:19:06.857727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f72096cb132'
down_revision = 'c703f5e8e0a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_forwarding_events',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('local_pubkey', sa.String(), nullable=True),
    sa.Column('channel_id_in', sa.BIGINT(), nullable=True),
    sa.Column('channel_id_out', sa.BIGINT(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount_in', sa.BIGINT(), nullable=True),
    sa.Column('amount_out', sa.BIGINT(), nullable=True),
    sa.Column('fee', sa.BIGINT(), nullable=True),
    sa.Column('last_index_offset', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('forwarding_events', sa.Column('amount_in', sa.BIGINT(), nullable=True))
    op.add_column('forwarding_events', sa.Column('amount_out', sa.BIGINT(), nullable=True))
    op.add_column('forwarding_events', sa.Column('channel_id_in', sa.BIGINT(), nullable=True))
    op.add_column('forwarding_events', sa.Column('channel_id_out', sa.BIGINT(), nullable=True))
    op.add_column('forwarding_events', sa.Column('last_index_offset', sa.BIGINT(), nullable=True))
    op.drop_column('forwarding_events', 'chan_id_out')
    op.drop_column('forwarding_events', 'chan_id_in')
    op.drop_column('forwarding_events', 'fee_msat')
    op.drop_column('forwarding_events', 'created_at')
    op.drop_column('forwarding_events', 'amt_in')
    op.drop_column('forwarding_events', 'amt_out')
    op.drop_column('forwarding_events', 'updated_at')
    op.drop_column('forwarding_events', 'last_offset_index')
    op.drop_column('forwarding_events', 'timestamp')
    op.add_column('forwarding_events', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forwarding_events', sa.Column('last_offset_index', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('forwarding_events', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('forwarding_events', sa.Column('amt_out', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('forwarding_events', sa.Column('amt_in', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('forwarding_events', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('forwarding_events', sa.Column('fee_msat', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('forwarding_events', sa.Column('chan_id_in', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('forwarding_events', sa.Column('chan_id_out', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('forwarding_events', 'last_index_offset')
    op.drop_column('forwarding_events', 'channel_id_out')
    op.drop_column('forwarding_events', 'channel_id_in')
    op.drop_column('forwarding_events', 'amount_out')
    op.drop_column('forwarding_events', 'amount_in')
    op.drop_table('etl_forwarding_events')
    # ### end Alembic commands ###
