"""add last offset index column

Revision ID: 2726bca3caf2
Revises: 99fe0fc09df1
Create Date: 2019-03-10 23:30:18.263049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2726bca3caf2'
down_revision = '99fe0fc09df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('last_offset_index', sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'last_offset_index')
    # ### end Alembic commands ###
