"""add last offset index column

Revision ID: 44d13e876306
Revises: ab052352ce1e
Create Date: 2019-03-10 23:58:25.615116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d13e876306'
down_revision = 'ab052352ce1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etl_invoices', sa.Column('last_index_offset', sa.BIGINT(), nullable=True))
    op.drop_column('etl_invoices', 'last_offset_index')
    op.add_column('invoices', sa.Column('last_index_offset', sa.BIGINT(), nullable=True))
    op.drop_column('invoices', 'last_offset_index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('last_offset_index', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('invoices', 'last_index_offset')
    op.add_column('etl_invoices', sa.Column('last_offset_index', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('etl_invoices', 'last_index_offset')
    # ### end Alembic commands ###
