"""add pending open channels

Revision ID: 5be154728d63
Revises: 92cb186822b5
Create Date: 2019-03-17 07:52:32.812163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be154728d63'
down_revision = '92cb186822b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_pending_open_channels',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('confirmation_height', sa.BIGINT(), nullable=True),
    sa.Column('commit_fee', sa.BIGINT(), nullable=True),
    sa.Column('commit_weight', sa.BIGINT(), nullable=True),
    sa.Column('fee_per_kw', sa.BIGINT(), nullable=True),
    sa.Column('remote_pubkey', sa.String(), nullable=True),
    sa.Column('local_pubkey', sa.String(), nullable=True),
    sa.Column('channel_point', sa.String(), nullable=True),
    sa.Column('capacity', sa.BIGINT(), nullable=True),
    sa.Column('local_balance', sa.BIGINT(), nullable=True),
    sa.Column('remote_balance', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_open_channels',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('confirmation_height', sa.BIGINT(), nullable=True),
    sa.Column('commit_fee', sa.BIGINT(), nullable=True),
    sa.Column('commit_weight', sa.BIGINT(), nullable=True),
    sa.Column('fee_per_kw', sa.BIGINT(), nullable=True),
    sa.Column('remote_pubkey', sa.String(), nullable=True),
    sa.Column('local_pubkey', sa.String(), nullable=True),
    sa.Column('channel_point', sa.String(), nullable=True),
    sa.Column('capacity', sa.BIGINT(), nullable=True),
    sa.Column('local_balance', sa.BIGINT(), nullable=True),
    sa.Column('remote_balance', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_open_channels')
    op.drop_table('etl_pending_open_channels')
    # ### end Alembic commands ###
