"""add initiator column

Revision ID: 5ccfaeb57936
Revises: fd2d86fd3332
Create Date: 2019-03-21 19:10:28.731887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ccfaeb57936'
down_revision = 'fd2d86fd3332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etl_open_channels', sa.Column('initiator', sa.Boolean(), nullable=True))
    op.add_column('open_channels', sa.Column('initiator', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('open_channels', 'initiator')
    op.drop_column('etl_open_channels', 'initiator')
    # ### end Alembic commands ###
