"""add lightning nodes

Revision ID: 6083cd58d962
Revises: 0f72096cb132
Create Date: 2019-03-23 22:00:17.887038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6083cd58d962'
down_revision = '0f72096cb132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_lightning_nodes',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pubkey', sa.String(), nullable=True),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lightning_nodes',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pubkey', sa.String(), nullable=True),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lightning_nodes')
    op.drop_table('etl_lightning_nodes')
    # ### end Alembic commands ###
