"""add constraints on open_channels

Revision ID: 608c8f412de8
Revises: a748534af84c
Create Date: 2019-03-24 16:37:15.440174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608c8f412de8'
down_revision = 'a748534af84c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('truncate table open_channels')
    op.alter_column('open_channels', 'capacity',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('open_channels', 'chan_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('open_channels', 'local_balance',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('open_channels', 'remote_balance',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('open_channels', 'total_satoshis_received',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('open_channels', 'total_satoshis_sent',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('open_channels', 'unsettled_balance',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_unique_constraint(None, 'open_channels', ['chan_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'open_channels', type_='unique')
    op.alter_column('open_channels', 'unsettled_balance',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('open_channels', 'total_satoshis_sent',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('open_channels', 'total_satoshis_received',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('open_channels', 'remote_balance',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('open_channels', 'local_balance',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('open_channels', 'chan_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('open_channels', 'capacity',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
