"""add unsettled_balance

Revision ID: 6cf1aa8fcdad
Revises: f90d89c9fdb2
Create Date: 2019-03-05 21:32:14.943849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf1aa8fcdad'
down_revision = 'f90d89c9fdb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etl_open_channels', sa.Column('unsettled_balance', sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etl_open_channels', 'unsettled_balance')
    # ### end Alembic commands ###
