"""Revision description

Revision ID: 7e8e5dafebc8
Revises: 
Create Date: 2019-03-01 07:42:49.917183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e8e5dafebc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balances',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pubkey', sa.String(), nullable=True),
    sa.Column('channel_balance', sa.Integer(), nullable=True),
    sa.Column('channel_pending_open_balance', sa.Integer(), nullable=True),
    sa.Column('wallet_total_balance', sa.Integer(), nullable=True),
    sa.Column('wallet_confirmed_balance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forwarding_events',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('local_pubkey', sa.String(), nullable=True),
    sa.Column('chan_id_in', sa.BIGINT(), nullable=True),
    sa.Column('chan_id_out', sa.BIGINT(), nullable=True),
    sa.Column('timestamp', sa.BIGINT(), nullable=True),
    sa.Column('amt_in', sa.BIGINT(), nullable=True),
    sa.Column('amt_out', sa.BIGINT(), nullable=True),
    sa.Column('fee', sa.BIGINT(), nullable=True),
    sa.Column('fee_msat', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('open_channels',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('chan_id', sa.BIGINT(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('local_pubkey', sa.String(), nullable=True),
    sa.Column('remote_pubkey', sa.String(), nullable=True),
    sa.Column('channel_point', sa.String(), nullable=True),
    sa.Column('capacity', sa.BIGINT(), nullable=True),
    sa.Column('local_balance', sa.BIGINT(), nullable=True),
    sa.Column('remote_balance', sa.BIGINT(), nullable=True),
    sa.Column('commit_fee', sa.BIGINT(), nullable=True),
    sa.Column('commit_weight', sa.BIGINT(), nullable=True),
    sa.Column('fee_per_kw', sa.BIGINT(), nullable=True),
    sa.Column('total_satoshis_sent', sa.BIGINT(), nullable=True),
    sa.Column('num_updates', sa.BIGINT(), nullable=True),
    sa.Column('csv_delay', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('open_channels')
    op.drop_table('forwarding_events')
    op.drop_table('balances')
    # ### end Alembic commands ###
