"""add constraints on open_channels

Revision ID: 8057b1003b67
Revises: a748534af84c
Create Date: 2019-03-24 16:45:01.322812

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8057b1003b67'
down_revision = 'a748534af84c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('truncate table open_channels')
    op.execute('truncate table etl_open_channels')
    op.alter_column('etl_open_channels', 'capacity',
                    existing_type=sa.BIGINT(),
                    server_default='0',
                    nullable=False)
    op.alter_column('etl_open_channels', 'local_balance',
                    existing_type=sa.BIGINT(),
                    server_default='0',
                    nullable=False)
    op.alter_column('etl_open_channels', 'remote_balance',
                    existing_type=sa.BIGINT(),
                    server_default='0',
                    nullable=False)
    op.alter_column('etl_open_channels', 'total_satoshis_received',
                    existing_type=sa.BIGINT(),
                    server_default='0',
                    nullable=False)
    op.alter_column('etl_open_channels', 'total_satoshis_sent',
                    existing_type=sa.BIGINT(),
                    server_default='0',
                    nullable=False)
    op.alter_column('etl_open_channels', 'unsettled_balance',
                    existing_type=sa.BIGINT(),
                    server_default='0',
                    nullable=False)
    op.alter_column('open_channels', 'capacity',
                    existing_type=sa.BIGINT(),
                    server_default='0',
                    nullable=False,
                    existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('open_channels', 'local_balance',
                    existing_type=sa.BIGINT(),
                    server_default='0',
                    nullable=False,
                    existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('open_channels', 'remote_balance',
                    existing_type=sa.BIGINT(),
                    server_default='0',
                    nullable=False,
                    existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('open_channels', 'total_satoshis_received',
                    existing_type=sa.BIGINT(),
                    server_default='0',
                    nullable=False,
                    existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('open_channels', 'total_satoshis_sent',
                    existing_type=sa.BIGINT(),
                    server_default='0',
                    nullable=False,
                    existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('open_channels', 'unsettled_balance',
                    existing_type=sa.BIGINT(),
                    server_default='0',
                    nullable=False,
                    existing_server_default=sa.text("'0'::bigint"))
    op.drop_constraint('open_channels_chan_id_key', 'open_channels',
                       type_='unique')
    op.drop_constraint('open_channels_chan_id_key1', 'open_channels',
                       type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('open_channels_chan_id_key1', 'open_channels',
                                ['chan_id'])
    op.create_unique_constraint('open_channels_chan_id_key', 'open_channels',
                                ['chan_id'])
    op.alter_column('open_channels', 'unsettled_balance',
                    existing_type=sa.BIGINT(),
                    server_default='0',
                    nullable=True,
                    existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('open_channels', 'total_satoshis_sent',
                    existing_type=sa.BIGINT(),
                    server_default='0',
                    nullable=True,
                    existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('open_channels', 'total_satoshis_received',
                    existing_type=sa.BIGINT(),
                    server_default='0',
                    nullable=True,
                    existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('open_channels', 'remote_balance',
                    existing_type=sa.BIGINT(),
                    server_default='0',
                    nullable=True,
                    existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('open_channels', 'local_balance',
                    existing_type=sa.BIGINT(),
                    server_default='0',
                    nullable=True,
                    existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('open_channels', 'capacity',
                    existing_type=sa.BIGINT(),
                    server_default='0',
                    nullable=True,
                    existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('etl_open_channels', 'unsettled_balance',
                    existing_type=sa.BIGINT(),
                    server_default='0',
                    nullable=True)
    op.alter_column('etl_open_channels', 'total_satoshis_sent',
                    existing_type=sa.BIGINT(),
                    server_default='0',
                    nullable=True)
    op.alter_column('etl_open_channels', 'total_satoshis_received',
                    existing_type=sa.BIGINT(),
                    server_default='0',
                    nullable=True)
    op.alter_column('etl_open_channels', 'remote_balance',
                    existing_type=sa.BIGINT(),
                    server_default='0',
                    nullable=True)
    op.alter_column('etl_open_channels', 'local_balance',
                    existing_type=sa.BIGINT(),
                    server_default='0',
                    nullable=True)
    op.alter_column('etl_open_channels', 'capacity',
                    existing_type=sa.BIGINT(),
                    server_default='0',
                    nullable=True)
    # ### end Alembic commands ###
