"""add last_offset_index column

Revision ID: 85714e28e854
Revises: 7e8e5dafebc8
Create Date: 2019-03-05 19:39:31.767397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85714e28e854'
down_revision = '7e8e5dafebc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forwarding_events', sa.Column('last_offset_index', sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forwarding_events', 'last_offset_index')
    # ### end Alembic commands ###
