"""add private and unsettled balance

Revision ID: 90bf02c89750
Revises: 0d10a4e705d2
Create Date: 2019-03-08 15:04:46.814506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90bf02c89750'
down_revision = '0d10a4e705d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('open_channels', sa.Column('private', sa.Boolean(), nullable=True))
    op.add_column('open_channels', sa.Column('unsettled_balance', sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('open_channels', 'unsettled_balance')
    op.drop_column('open_channels', 'private')
    # ### end Alembic commands ###
