"""change to active peers

Revision ID: 92cb186822b5
Revises: c69eb956552d
Create Date: 2019-03-16 18:34:00.608890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92cb186822b5'
down_revision = 'c69eb956552d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_peers',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('remote_pubkey', sa.String(), nullable=True),
    sa.Column('local_pubkey', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('bytes_sent', sa.BIGINT(), nullable=True),
    sa.Column('bytes_recv', sa.BIGINT(), nullable=True),
    sa.Column('sat_sent', sa.BIGINT(), nullable=True),
    sa.Column('sat_recv', sa.BIGINT(), nullable=True),
    sa.Column('inbound', sa.Boolean(), nullable=True),
    sa.Column('ping_time', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etl_active_peers',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('remote_pubkey', sa.String(), nullable=True),
    sa.Column('local_pubkey', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('bytes_sent', sa.BIGINT(), nullable=True),
    sa.Column('bytes_recv', sa.BIGINT(), nullable=True),
    sa.Column('sat_sent', sa.BIGINT(), nullable=True),
    sa.Column('sat_recv', sa.BIGINT(), nullable=True),
    sa.Column('inbound', sa.Boolean(), nullable=True),
    sa.Column('ping_time', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('balances')
    op.drop_table('peers')
    op.drop_table('etl_peers')
    op.add_column('inbound_capacity_request', sa.Column('keep_open_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbound_capacity_request', 'keep_open_until')
    op.create_table('etl_peers',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('remote_pubkey', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('local_pubkey', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bytes_sent', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('bytes_recv', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('sat_sent', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('sat_recv', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('inbound', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ping_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='etl_peers_pkey')
    )
    op.create_table('peers',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bytes_recv', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('bytes_sent', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('inbound', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('local_pubkey', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ping_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('remote_pubkey', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sat_recv', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('sat_sent', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='peers_pk')
    )
    op.create_table('balances',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pubkey', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('channel_balance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('channel_pending_open_balance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wallet_total_balance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wallet_confirmed_balance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='balances_pkey')
    )
    op.drop_table('etl_active_peers')
    op.drop_table('active_peers')
    # ### end Alembic commands ###
