"""add channel edges

Revision ID: 9434b12b1df3
Revises: 6083cd58d962
Create Date: 2019-03-23 22:31:19.129410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9434b12b1df3'
down_revision = '6083cd58d962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_edges',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('channel_id', sa.BIGINT(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('node1_pubkey', sa.String(), nullable=True),
    sa.Column('node2_pubkey', sa.String(), nullable=True),
    sa.Column('chan_point', sa.String(), nullable=True),
    sa.Column('capacity', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etl_channel_edges',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('channel_id', sa.BIGINT(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('node1_pubkey', sa.String(), nullable=True),
    sa.Column('node2_pubkey', sa.String(), nullable=True),
    sa.Column('chan_point', sa.String(), nullable=True),
    sa.Column('capacity', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etl_channel_edges')
    op.drop_table('channel_edges')
    # ### end Alembic commands ###
