"""add peers table

Revision ID: 96669fcbff54
Revises: 6cf1aa8fcdad
Create Date: 2019-03-07 17:48:40.049650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96669fcbff54'
down_revision = '6cf1aa8fcdad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peers',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pubkey', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('pubkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peers')
    # ### end Alembic commands ###
