"""add invoices etl table

Revision ID: 99fe0fc09df1
Revises: 4e17591a057f
Create Date: 2019-03-10 21:53:25.226510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99fe0fc09df1'
down_revision = '4e17591a057f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_invoices',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('local_pubkey', sa.String(), nullable=True),
    sa.Column('r_hash', sa.String(), nullable=True),
    sa.Column('memo', sa.String(), nullable=True),
    sa.Column('r_preimage', sa.String(), nullable=True),
    sa.Column('value', sa.BIGINT(), nullable=True),
    sa.Column('settled', sa.Boolean(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settle_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_request', sa.String(), nullable=True),
    sa.Column('description_hash', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('expiry', sa.BIGINT(), nullable=True),
    sa.Column('fallback_addr', sa.String(), nullable=True),
    sa.Column('cltv_expiry', sa.BIGINT(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('add_index', sa.BIGINT(), nullable=True),
    sa.Column('settle_index', sa.BIGINT(), nullable=True),
    sa.Column('amt_paid_sat', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etl_invoices')
    # ### end Alembic commands ###
