"""add last offset index column

Revision ID: ab052352ce1e
Revises: 2726bca3caf2
Create Date: 2019-03-10 23:56:00.626163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab052352ce1e'
down_revision = '2726bca3caf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etl_invoices', sa.Column('last_offset_index', sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etl_invoices', 'last_offset_index')
    # ### end Alembic commands ###
