"""add invoices table

Revision ID: b2b495894875
Revises: 18ff9ab5e575
Create Date: 2019-03-10 18:40:40.686366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b495894875'
down_revision = '18ff9ab5e575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('r_hash', sa.String(), nullable=False),
    sa.Column('memo', sa.String(), nullable=True),
    sa.Column('r_preimage', sa.String(), nullable=True),
    sa.Column('value', sa.BIGINT(), nullable=True),
    sa.Column('settled', sa.Boolean(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settle_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_request', sa.String(), nullable=True),
    sa.Column('description_hash', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('expiry', sa.BIGINT(), nullable=True),
    sa.Column('fallback_addr', sa.String(), nullable=True),
    sa.Column('cltv_expiry', sa.BIGINT(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('add_index', sa.BIGINT(), nullable=True),
    sa.Column('settle_index', sa.BIGINT(), nullable=True),
    sa.Column('amt_paid', sa.BIGINT(), nullable=True),
    sa.Column('amt_paid_sat', sa.BIGINT(), nullable=True),
    sa.Column('amt_paid_msat', sa.BIGINT(), nullable=True),
    sa.Column('invoice_state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('r_hash')
    )
    op.create_foreign_key(None, 'inbound_capacity_request', 'invoices', ['invoice_r_hash'], ['r_hash'])
    op.drop_column('inbound_capacity_request', 'payment_request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbound_capacity_request', sa.Column('payment_request', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inbound_capacity_request', type_='foreignkey')
    op.drop_table('invoices')
    # ### end Alembic commands ###
