"""add peers polling

Revision ID: c69eb956552d
Revises: 44d13e876306
Create Date: 2019-03-16 10:43:59.536255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c69eb956552d'
down_revision = '44d13e876306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_peers',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('remote_pubkey', sa.String(), nullable=True),
    sa.Column('local_pubkey', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('bytes_sent', sa.BIGINT(), nullable=True),
    sa.Column('bytes_recv', sa.BIGINT(), nullable=True),
    sa.Column('sat_sent', sa.BIGINT(), nullable=True),
    sa.Column('sat_recv', sa.BIGINT(), nullable=True),
    sa.Column('inbound', sa.Boolean(), nullable=True),
    sa.Column('ping_time', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('open_channels_local_pubkey_fkey', 'open_channels', type_='foreignkey')
    op.drop_constraint('open_channels_remote_pubkey_fkey', 'open_channels', type_='foreignkey')
    op.add_column('peers', sa.Column('address', sa.String(), nullable=True))
    op.add_column('peers', sa.Column('bytes_recv', sa.BIGINT(), nullable=True))
    op.add_column('peers', sa.Column('bytes_sent', sa.BIGINT(), nullable=True))
    op.add_column('peers', sa.Column('id', sa.BIGINT(), nullable=False))
    op.add_column('peers', sa.Column('inbound', sa.Boolean(), nullable=True))
    op.add_column('peers', sa.Column('local_pubkey', sa.String(), nullable=True))
    op.add_column('peers', sa.Column('ping_time', sa.BIGINT(), nullable=True))
    op.add_column('peers', sa.Column('remote_pubkey', sa.String(), nullable=True))
    op.add_column('peers', sa.Column('sat_recv', sa.BIGINT(), nullable=True))
    op.add_column('peers', sa.Column('sat_sent', sa.BIGINT(), nullable=True))
    op.drop_column('peers', 'pubkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peers', sa.Column('pubkey', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('peers', 'sat_sent')
    op.drop_column('peers', 'sat_recv')
    op.drop_column('peers', 'remote_pubkey')
    op.drop_column('peers', 'ping_time')
    op.drop_column('peers', 'local_pubkey')
    op.drop_column('peers', 'inbound')
    op.drop_column('peers', 'id')
    op.drop_column('peers', 'bytes_sent')
    op.drop_column('peers', 'bytes_recv')
    op.drop_column('peers', 'address')
    op.create_foreign_key('open_channels_remote_pubkey_fkey', 'open_channels', 'peers', ['remote_pubkey'], ['pubkey'])
    op.create_foreign_key('open_channels_local_pubkey_fkey', 'open_channels', 'peers', ['local_pubkey'], ['pubkey'])
    op.drop_table('etl_peers')
    # ### end Alembic commands ###
