"""add lightning addresses

Revision ID: c703f5e8e0a6
Revises: 5ccfaeb57936
Create Date: 2019-03-22 13:50:16.538388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c703f5e8e0a6'
down_revision = '5ccfaeb57936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_lightning_addresses',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('pubkey', sa.String(), nullable=True),
    sa.Column('network', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lightning_addresses',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('pubkey', sa.String(), nullable=True),
    sa.Column('network', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lightning_addresses')
    op.drop_table('etl_lightning_addresses')
    # ### end Alembic commands ###
