"""add smart fee estimates

Revision ID: e9bc76e1cfd2
Revises: 5be154728d63
Create Date: 2019-03-17 09:21:46.182030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9bc76e1cfd2'
down_revision = '5be154728d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_smart_fee_estimates',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('conf_target', sa.BIGINT(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('fee_rate', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smart_fee_estimates',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('conf_target', sa.BIGINT(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('fee_rate', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smart_fee_estimates')
    op.drop_table('etl_smart_fee_estimates')
    # ### end Alembic commands ###
