"""add status column

Revision ID: fd2d86fd3332
Revises: 49a779800b48
Create Date: 2019-03-21 11:32:32.604209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd2d86fd3332'
down_revision = '49a779800b48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbound_capacity_request', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbound_capacity_request', 'status')
    # ### end Alembic commands ###
